name: Build
on:
- push
- pull_request
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macOS-latest
        python-version:
        - "3.8"
        - "3.11"
        networkx-version:
        - "1.*"
        - "2.*"
        exclude:
        - python-version: "3.11"
          networkx-version: "1.*"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install networkx==${{ matrix.networkx-version }}
        python -m pip install --upgrade pip
        pip install ".[dev]"
    - name: Run pre-commit
      if: matrix.python-version == '3.11'
      uses: pre-commit/action@v3.0.0
    - name: Test with pytest
      run: pytest --color=yes
