name: Release
on:
  release:
    types:
    - published
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/obonet/
    permissions:
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install build wheel
    - name: Build package
      run: python -m build --sdist --wheel --outdir=dist
    - name: Deploy package
      if: '!github.event.repository.fork'
      uses: pypa/gh-action-pypi-publish@release/v1
